import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Figma Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={styles.title}>Color Pallet</p>
      <main className={`${styles.main}`}>
        <div className={styles.boxContainer}>
          <div className={styles.grayBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.boxContainer}>
          <div className={styles.greenBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.boxContainer}>
          <div className={styles.pinkBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.boxContainer}>
          <div className={styles.purpleBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
      </main>
    </>
  );
}
