import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Figma Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={styles.title}>Figma Tokens Demo</p>
      <main className={`${styles.main}`}>
        <div className={styles.boxContainer}>
          <div className={styles.grayBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.boxContainer}>
          <div className={styles.greenBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.boxContainer}>
          <div className={styles.pinkBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.boxContainer}>
          <div className={styles.purpleBox}>
            <div className={styles.ten}/>
            <div className={styles.twenty}/>
            <div className={styles.thirty}/>
            <div className={styles.forty}/>
            <div className={styles.fifty}/>
            <div className={styles.sixty}/>
            <div className={styles.seventy}/>
            <div className={styles.eighty}/>
          </div>
        </div>
        <div className={styles.textBox}>
          <p className={styles.heading}>見出し1のみ文字色として使用</p>
          <p className={styles.default}>本文など、デフォルトの文字色として使用</p>
          <p className={styles.subtext}>サブテキストに使用</p>
          <p className={styles.textlink}>テキストリンク、最小文字の注記に使用</p>
          <p className={styles.notes}>注意書きに使用</p>
          <p className={styles.form}>入力欄、プレースホルダのテキストに使用</p>
          <p className={styles.white}>白文字いしたい時に使用</p>
          <p className={styles.attention}>ログインや申請フォーム等のシステムに失敗した際に使用</p>
        </div>
      </main>
    </>
  );
}
